services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY:-vKpsikScqRUt2CdC}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///plants.db}
      - DATABASE_PATH=${DATABASE_PATH:-plants.db}
    volumes:
      - db_data:/app/database # Mount the named volume to persist database data
    restart: unless-stopped
    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: /app
          ignore:
            - "*.db"

volumes:
  db_data: # Named volume for persistent data
    driver: local
