{
 "title": "Maker Plant Universe",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Soil Moisture",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "smart_plants",
     "rawSql": "SELECT DISTINCT ON (name) \n    name,\n    value\nFROM sensor_values \nWHERE sensor_type = 'moisture' \n    AND $__timeFilter(\"timestamp\")\nORDER BY name, timestamp DESC\n"
    }
   ]
  },
  {
   "title": "Moisture",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "smart_plants",
     "rawSql": "SELECT\n  $__time(\"timestamp\"),\n  name,\n  value AS \" \"\nFROM\n  sensor_values\nWHERE\n  sensor_type='moisture'\nORDER BY\n  1;"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "smart_plants",
     "rawSql": "SELECT DISTINCT ON (name) \n    name,\n    value\nFROM sensor_values \nWHERE sensor_type = 'battery_voltage'\nORDER BY name, timestamp DESC\n"
    }
   ]
  }
 ]
}